[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]

[frontends]
  [frontends.spa]
  entryPoints = ["http"]
  backend = "dev_server"
  [frontends.api]
  entryPoints = ["http"]
  backend = "django"
    [frontends.api.routes.api]
    rule = "PathPrefix: /api/"
  [frontends.ws]
  entryPoints = ['http']
  backend = "ws"
    [frontends.ws.routes.ws]
    rule = "PathPrefix: /ws"

[backends]
  [backends.dev_server]
    [backends.dev_server.servers]
      [backends.dev_server.servers.elmreactor]
      url = "http://localhost:8081"

  [backends.django]
    [backends.django.servers]
      [backends.django.servers.server1]
      url = "http://localhost:8082"

  [backends.ws]
    [backends.ws.servers]
      [backends.ws.servers.server1]
      url = "http://localhost:47187"
